import { Providers } from "@/redux/provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import prompts from "@/utils/prompts";
import { Story } from "@/types/story.type";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const data = await fetchData();

  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen flex flex-col`}>
        <div className="flex flex-1">
          <Providers initialData={data}>{children}</Providers>
        </div>
        <Footer />
      </body>
    </html>
  );
}
const fetchData = async (): Promise<Story[]> => {
  const stories = {
    "story-1":
      "In a dusty library, a magical book sat forgotten. As soon as it was opened, readers found themselves amid the tales they had chosen. Dragons soared overhead, pirates raced across stormy seas, and castles materialized before their eyes. Laughter and wonder echoed through each page, but with every adventure came a bit of chaos. The line between fiction and reality blurred as characters spilled into the real world. Soon, readers became heroes, learning to wield newfound powers. As the final page turned, they returned home, hearts brimming with memories. The magical book's stories had left an indelible mark on their lives.",
    "story-2":
      "Amid the ruins of civilization, a group of survivors stumbled upon an entrance, concealed beneath rubble. Inside, a dazzling sanctuary awaited – an underground haven. Advanced technology hummed around them, providing sustenance and safety. Grateful, they embraced their new home, but doubts surfaced. Whispers spoke of a hidden purpose to their sanctuary, an enigmatic agenda. As they probed deeper, they uncovered unsettling truths: the sanctuary's creators aimed to manipulate and control, exploiting survivors for a grand design. United, the survivors challenged their captors, sparking a battle for freedom. In the subterranean depths, a choice was made – to reclaim their destinies and emerge from darkness into a new dawn.",
    "story-3":
      "Trapped in time's embrace, Alex, a curious time traveler, found themselves stranded in the distant past. Armed with their wits and a malfunctioning time device, they embarked on a journey through epochs. In ancient Egypt, they marveled at colossal pyramids. Among medieval knights, they dodged duels and intrigue. The Renaissance brought encounters with da Vinci and his genius. Amid industrial revolution, steam-powered marvels astounded. Every era posed challenges – language barriers, customs to adapt to, and the need to avoid disrupting history. Determined, Alex embraced each period's lessons and connections, piecing together a way home. Their journey through time was a testament to human resilience and the unbreakable spirit of exploration.",
  };
  return prompts.map((prompt) => ({
    id: prompt.id,
    title: prompt.title,
    prompt: prompt.description,
    body: stories[prompt.id],
  }));
};
